config/routes.rb
Railsplex::Application.routes.draw do
  resources :recipes

  devise_for :users

  resources :defines
  get 'definitions', to: 'defines#index'
  get 'define/:id', to: 'defines#show'
  root to: 'welcome#index'

end

app/models/ability.rb
class Ability
	include CanCan::Ability

	def initialize(user)
		user ||= User.new #guest user

		if user.admin?
			can :manage, :all
		else
			can :read, :all
			#can :create, Define do |d|
			#	d.try(:user) == user
			#end
			#can :update, Define do |d|
			#	d.try(:user) == user
			#end
			#can :destroy, Define do |d|
			#	d.try(:user) == user
			#end
		end
		
	end
end

app/models/define.rb
class Define < ActiveRecord::Base
  attr_accessible :definition, :term, :image, :relevance, :category, :user_id
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :definition, :term, :relevance, :category, presence: true
  validates :term, uniqueness: true

  	def self.text_search(query)
	  if query.present?
	    where("term @@ :q or category @@ :q or definition @@ :q", q: query) #.order(:term)
	  else
	    scoped
	  end
	end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  attr_accessible :recipe, :title, :user_id
  validates :recipe, :title, presence: true

  #before_save :get_user_for_definition

    #def get_user_for_definition
	#	self.user_id = current_user.id
	#	self.save
	#end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin
  # attr_accessible :title, :body
  has_many :defines
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
  	flash[:error] = "No donuts for you"
  	redirect_to root_url
  end
end

app/controllers/defines_controller.rb
class DefinesController < ApplicationController
  # GET /defines
  # GET /defines.json
  before_filter :authenticate_user!, except: [:index, :show]
  
  load_and_authorize_resource
  
  def index
    if params[:query]
      @defines = Define.text_search(params[:query])
    elsif params[:category]
      @defines = Define.where(category: params[:category]).order(:relevance)
    else
      @defines = Define.all(order: [:relevance])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @defines }
      format.js
    end
  end

  # GET /defines/1
  # GET /defines/1.json
  def show
    @define = Define.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @define }
    end
  end

  # GET /defines/new
  # GET /defines/new.json
  def new
    @define = Define.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @define }
    end
  end

  # GET /defines/1/edit
  def edit
    @define = Define.find(params[:id])
  end

  # POST /defines
  # POST /defines.json
  def create
    @define = Define.new(params[:define])

    respond_to do |format|
      if @define.save
        format.html { redirect_to @define, notice: 'Define was successfully created.' }
        format.json { render json: @define, status: :created, location: @define }
      else
        format.html { render action: "new" }
        format.json { render json: @define.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /defines/1
  # PUT /defines/1.json
  def update
    @define = Define.find(params[:id])

    respond_to do |format|
      if @define.update_attributes(params[:define])
        format.html { redirect_to @define, notice: 'Define was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @define.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /defines/1
  # DELETE /defines/1.json
  def destroy
    @define = Define.find(params[:id])
    @define.destroy

    respond_to do |format|
      format.html { redirect_to defines_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # GET /recipes
  # GET /recipes.json
  before_filter :authenticate_user!, except: [:index, :show]
  
  load_and_authorize_resource
  
  def index
    @recipes = Recipe.all(order: :id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.json
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render json: @recipe, status: :created, location: @recipe }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.json
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ==== Examples
  # glyph(:share_alt)
  # # => <i class="icon-share-alt"></i>
  # glyph(:lock, :white)
  # # => <i class="icon-lock icon-white"></i>
  
	def glyph(*names)
    	content_tag :i, nil, class: names.map{|name| "icon-#{name.to_s.gsub('_','-')}" }
  	end
end

app/helpers/defines_helper.rb
module DefinesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/defines/_form.html.erb
<%= form_for(@define, html: {multipart: true}) do |f| %>
  <% if @define.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@define.errors.count, "error") %> prohibited this define from being saved:</h2>

      <ul>
      <% @define.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="controls controls-row">
    <%= f.text_field :term, class: "span3", placeholder: "term" %>
    <%= f.select(:category, options_for_select(['ruby', 'rails', 'html5', 'css3', 'github', 'heroku']), class: "span1") %>
    <%= f.text_field :relevance, class: "span1", placeholder: "0" %>
  </div>
  <div class="controls">
    <%= f.text_area :definition, class: "input-xxlarge", placeholder: "definition here" %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="form-actions">
    <%= f.submit(class: "btn btn-primary") %>
  </div>
<% end %>

app/views/defines/_index.html.erb
<div id="definition">
  <div class="media">
    <% @defines.each do |define| %>
      <a class="pull-left">
        <% if define.image? %>
          <%= image_tag define.image_url.to_s, id:"side" %>
        <% else %>
          <%= image_tag("default.png", id:"side") %>
        <% end %>
      </a>
    <div class="media-body">
      <h4 class="media-heading"><%= link_to image_tag("#{define.category}_little.png"), defines_path(category: define.category) %><%= link_to define.term, "define/#{define.id}" %></h4>
        <dd><%= sanitize(define.definition) %></dd>
    </div>
    <p></p>
    <% end %>
  </div>
</div>

app/views/defines/edit.html.erb
<div class="span12">
<h1>Editing definition</h1>

	<div class="span6">
		<%= render 'form' %>

		<div class="form-actions">
			<%= link_to 'Show', @define, class: "btn" %>
			<%= link_to 'Back', defines_path, class: "btn" %>
		</div>
	</div>
</div>

app/views/defines/index.html.erb
<div class="container">
  <div class="navbar text-center">
    <ul class="inline">
      <h2 class="text-error">Pick one</h2>
        <li><%= link_to image_tag("ruby.png"), defines_path(category: 'ruby') %></li>
        <li><%= link_to image_tag("rails.png"), defines_path(category: 'rails') %></li>
        <li><%= link_to image_tag("html5.png"), defines_path(category: 'html5') %></li>
        <li><%= link_to image_tag("css3.png"), defines_path(category: 'css3') %></li>
        <li><%= link_to image_tag("github.png"), defines_path(category: 'github') %></li>
        <li><%= link_to image_tag("heroku.png"), defines_path(category: 'heroku') %></li>
    </ul>
  </div>
</div>

<div class="span10">
<ul>
  <li>
  <div id="definition_index">
    <div class="media">
      <% @defines.each do |define| %>
      <a class="pull-left">
        <% if define.image? %>
          <%= image_tag define.image_url.to_s, id:"side" %>
        <% else %>
          <%= image_tag("default.png", id:"side") %>
        <% end %>
      </a>
      <div class="media-body">
        <h4 class="media-heading"><%= link_to image_tag("#{define.category}_little.png"), defines_path(category: define.category) %><%= link_to define.term, "define/#{define.id}" %></h4>
          <dd><%= sanitize(define.definition) %></dd>
        <p>
          <% if can? :update, define %>
          <%= link_to 'Edit', edit_define_path(define), class: "btn" %> 
          <% end %>
          <% if can? :destroy, define %>
          <%= link_to 'Destroy', define, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %>
          <% end %>
        </p>
      </div>
      <p></p>
      <% end %>
    </div>
  </div>
  </li>
</ul>
  <% if can? :create, @defines %>
    <%= link_to 'New Definition', new_define_path, class: "btn btn-success" %>
  <% end %>
</div>

app/views/defines/new.html.erb
<div class="span12">
	<h1>New definition</h1>

	<div class="span6">
		<%= render 'form' %>

		<div class="form-actions">
			<%= link_to 'Back', defines_path, class: "btn" %>
		</div>
	</div>
</div>

app/views/defines/show.html.erb
<div class="span10">
	<div class="media">
	  <a class="pull-left">
        <% if @define.image? %>
          <%= image_tag @define.image_url.to_s, id:"side" %>
        <% else %>
          <%= image_tag("default.png", id:"side") %>
        <% end %>
      </a>
	  <div class="media-body">
	    <h4 class="media-heading"><%= image_tag("#{@define.category}_little.png") %><%= @define.term %></h4>
	      <%= sanitize(@define.definition) %>
	      <small class="text-warning">relevance: <%= @define.relevance %></small>
	    <p>
	      <%= link_to 'Back', definitions_path, class: "btn" %> 
	      
	      <% if can? :create, @define %>
	      	<%= link_to 'New Definition', new_define_path, class: "btn btn-success" %> 
	      <% end %>
	      <% if can? :update, @define %>
	      	<%= link_to 'Edit', edit_define_path(@define), class: "btn" %> 
	      <% end %>
	      <% if can? :destroy , @define %>
	      	<%= link_to 'Destroy', @define, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %>
	      <% end %>

	    </p>
	  </div>

	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsplex: Rails explained by its parts</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-static-top"> <!-- modified "navbar navbar-fixed-top" -->
	<div class="navbar-inner">
		<div class="container">
			<div class="row">
				<div class="span12">
					<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</a>					
					
					<a class="brand" href="/"><%= image_tag("logo.png") %>Railsplex</a>
				
					<div class="btn-group dropdown pull-right">
						<% if user_signed_in? %>						
							<a class="btn btn-danger"><i class="icon-user icon-white"></i>  <%= current_user.email %></a>
							<a class="btn btn-danger dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
							<ul class="dropdown-menu">
							 <li><%= link_to glyph(:"warning-sign") + " Logout", destroy_user_session_path, metho: :delete %></li>
							</ul>
						<% end %>
					</div>
					
					
					<div class="nav-collapse">		
						<div id="search">
							<%= form_tag defines_path, class: "form-search", remote: true, method: :get do %>
							  <div class="input-append">
							    <%= text_field_tag :query, params[:query], class: "input-medium search-query", id: "appendedInputButtons", placeholder: "search: Programming Ingredients" %>
							    <button type="submit" class="btn btn-danger">
					  				<i class="icon-search icon-white"></i> ingredients
								</button>
								<!-- above substitutes this and add the ability to add gyphs on it
								<%= submit_tag "Find Definition", term: nil, class: "btn btn-danger" %>
								-->
							  </div>
							<% end %>
						</div>
					</div>	

				</div>
			</div>
		</div>
	</div>
</div>

<div class="container">
	<% flash.each do |name, msg| %>
		<div class="alert alert-<%=(name == :notice && 'success' or name == :warning && 'warning' or name == :info && 'info' or 'error')%>">
			<button class="close" data-dismiss="alert">&times;</button>
			<%= msg %>
		</div>
	<% end %>

	<div class="row">
		<div class="span12">
			<div class="span12">
				<div class="span10 results">
				</div>
			</div>
			<%= yield %>
		</div>	
	</div>
</div>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.text_field :title, class: "input-xxlarge", placeholder: "Title" %>
  </div>
  <div class="field">
    <%= f.text_area :recipe, class: "input-xxlarge", placeholder: "The Recipe" %>
  </div>
  <div class="form-actions">
    <%= f.submit(class: "btn btn-primary") %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<div class="span12">
	<h1>Editing recipe</h1>

	<div class="span6">
		<%= render 'form' %>

		<div class="form-actions">
			<%= link_to 'Show', @recipe, class: "btn" %>
			<%= link_to 'Back', recipes_path, class: "btn" %>
		</div>
	</div>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <div class="span3">
    <ul class="nav nav-list">
      <li class="nav-header"><h5>Last Recipes</h5></li>
      <li class="divider"></li>
      <% @recipes.each do |recipe| %>
      <li><%= link_to glyph(:book) + " #{recipe.title}", recipe, class: "muted" %></li>
      <% end %>
    </ul>
  </div>

<li class="span1" style="list-style: none;"></li>

  <ul class="span8 thumbnails">
    <% @recipes.each_with_index do |recipe, index| %>
    
    <li class="span6">
      <span class="label label-important pull-right"><h5><%= glyph(:"book", :white) + " #{index}" %></h5></span>
      <div class="thumbnail">
          
            <p>
              <h3 class="text-error text-left"><%= recipe.title %></h3>
            </p>
            <p>
              <dd><%= sanitize(truncate(recipe.recipe, length: 140, separator: ' ')) %>
              <b><%= link_to "continue >", recipe %></b></dd>
            </p>
          
      </div>
    </li>
    <% end %>
  </ul>
</div>

<% if can? :create, @receipes %>
  <%= link_to 'New Recipe', new_recipe_path, class: "btn btn-success" %>
<% end %>

app/views/recipes/new.html.erb
<div class="span12">
	<h1>New recipe</h1>

	<div class="span6">
		<%= render 'form' %>

		<div class="form-actions">
			<%= link_to 'Back', recipes_path, class: "btn" %>
		</div>
	</div>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <ul class="thumbnails">
    <li class="span2"></li>
    <li class="span8">
      <div class="thumbnail">
          <p>
            <h2 class="text-error text-center"><%= @recipe.title %></h2>
          </p>

          <dd><%= sanitize(@recipe.recipe) %></dd>

          <p class="pager">
          	<%= link_to 'Back', recipes_path, class: "btn" %>
          	<% if can? :create, @receipes %>
  				    <%= link_to 'New Recipe', new_recipe_path, class: "btn btn-success" %>
			      <% end %>
          	<% if can? :update, @recipe %>
          		<%= link_to 'Edit', edit_recipe_path(@recipe), class: "btn" %>
          	<% end %>
          	<% if can? :destroy, @recipe %>
          		<%= link_to 'Destroy', @recipe, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %>
          	<% end %>
          </p>
      </div>
    </li>
    <li class="span2"></li>
  </ul>
</div>

app/views/welcome/index.html.erb
<div class="text-center" id="image">
	<%= image_tag("index_2.png") %>
</div>
<footer class="footer">
<div class="container">
	<ul class="thumbnails">
		<li class="span4">
			<div class="thumbnail">
			    <p>
			      <h3 class="text-error text-center">Ingredients</h3>
			    </p>
			      <%= image_tag("ingredients.png") %>
			  	
			     <h3 class="text-center">1. Definitions</h3>
			      <p>
			      	<i>Definitions</i> is an <b>easy to digest snack</b> to get better to Ruby, Rails and Programming - in few lines. Whether you are a newbie or just want to remember something cool.
			      </p>
			      <p>
			      	<a href="/definitions" class="btn btn-danger btn-block">Find All</a>
			      </p>
			</div>
		</li>
			  
		<li class="span4">
			<div class="thumbnail">
			    <p>
			      <h3 class="text-error text-center">Cookbook</h3>
			    </p>
			      <%= image_tag("cookbook.png") %>
			  	
			      <h3 class="text-center">2. Explained</h3>
			      <p>
			      	<i>Rails Explained</i> is like a <b>meaty sandwich</b> with barbecue sauce <b>when you are hungry</b> for a more in deep - a bit ludic - explanation about the definitions section.
			      </p>
			      <p>
			      	<a href="/recipes" class="btn btn-danger btn-block">Try The Recipes</a>
			      </p>
			</div>
		</li>

		<li class="span4">
			<div class="thumbnail">
			    <p>
			      <h3 class="text-error text-center">Le Chef</h3>
			    </p>
			      <%= image_tag("chef.png") %>
			  	
			      <h3 class="text-center">3. By who loves it <a href="mailto:celsodessa@gmail.com" class="btn btn-small btn-success">Hire Me!</a></h3>
			      <p>
			      	<i>When</i> <b>I was a newbie to Rails</b> I was a newbie to programming also, then <b>I had to cook</b> a lot of <b>information</b> to get it right. Then I realized that Rails...
			      </p>
			      <p>
			      	<a href="/recipes/1" class="btn btn-danger btn-block">Continue Reading...</a>
			      </p>
			</div>
		</li>
	</ul>
</div>
</footer>